# Generated by Django 2.1 on 2018-09-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appauthrequest',
            name='user_side_code',
            field=models.CharField(max_length=4),
        ),
    ]
