# Generated by Django 2.1 on 2018-09-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyauth', '0002_auto_20180904_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='appauthrequest',
            name='user_side_token',
            field=models.CharField(default='', max_length=32),
        ),
    ]
