# Generated by Django 2.1 on 2018-09-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyauth', '0003_appauthrequest_user_side_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appauthrequest',
            name='expiry_date',
            field=models.DateTimeField(default=None),
        ),
    ]
