# Generated by Django 2.0.5 on 2018-05-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(height_field='image_height', upload_to='uploads/%Y/%m/%d/', width_field='image_width')),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
            ],
        ),
    ]
