# Generated by Django 2.0.5 on 2018-06-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
