# Generated by Django 2.0.5 on 2018-06-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='preview',
            field=models.ImageField(height_field='preview_height', null=True, upload_to='', width_field='preview_width'),
        ),
        migrations.AddField(
            model_name='photo',
            name='preview_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='preview_width',
            field=models.IntegerField(default=0),
        ),
    ]
