# Generated by Django 2.0.5 on 2018-07-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_comment'),
        ('photo', '0002_auto_20180628_1951'),
    ]

    operations = [
    ]
